/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Djp0526ObgRouteImport } from './routes/djp0526-obg'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AdvIaRouteImport } from './routes/adv-ia'
import { Route as IndexRouteImport } from './routes/index'

const Djp0526ObgRoute = Djp0526ObgRouteImport.update({
  id: '/djp0526-obg',
  path: '/djp0526-obg',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvIaRoute = AdvIaRouteImport.update({
  id: '/adv-ia',
  path: '/adv-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adv-ia': typeof AdvIaRoute
  '/design-system': typeof DesignSystemRoute
  '/djp0526-obg': typeof Djp0526ObgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adv-ia': typeof AdvIaRoute
  '/design-system': typeof DesignSystemRoute
  '/djp0526-obg': typeof Djp0526ObgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adv-ia': typeof AdvIaRoute
  '/design-system': typeof DesignSystemRoute
  '/djp0526-obg': typeof Djp0526ObgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adv-ia' | '/design-system' | '/djp0526-obg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adv-ia' | '/design-system' | '/djp0526-obg'
  id: '__root__' | '/' | '/adv-ia' | '/design-system' | '/djp0526-obg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvIaRoute: typeof AdvIaRoute
  DesignSystemRoute: typeof DesignSystemRoute
  Djp0526ObgRoute: typeof Djp0526ObgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/djp0526-obg': {
      id: '/djp0526-obg'
      path: '/djp0526-obg'
      fullPath: '/djp0526-obg'
      preLoaderRoute: typeof Djp0526ObgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adv-ia': {
      id: '/adv-ia'
      path: '/adv-ia'
      fullPath: '/adv-ia'
      preLoaderRoute: typeof AdvIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvIaRoute: AdvIaRoute,
  DesignSystemRoute: DesignSystemRoute,
  Djp0526ObgRoute: Djp0526ObgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
